export interface CasinoLobbyGame {
  id: string;
  title: string;
  category: 'Slots' | 'Table Games' | 'Instant Play' | 'Dice & Plinko' | 'Retro Arcade Live';
  rtp: number; // percentage
  provider: string;
  volatility: 'Low' | 'Medium' | 'High' | 'Extreme';
  maxMultiplier: string;
  popularityScore: number;
  houseEdge: string;
  releaseYear: number;
  tagline: string;
  iconSymbol: string;
}

export const CASINO_LOBBY_GAMES_100: CasinoLobbyGame[] = [
  // SLOTS (25 games)
  { id: 'c1', title: 'Mega Moolah On-Chain', category: 'Slots', rtp: 96.5, provider: 'Satoshi Soft v1998', volatility: 'High', maxMultiplier: '15000x', popularityScore: 98, houseEdge: '3.5%', releaseYear: 1998, tagline: 'Classic progressive jackpot emulation with distributed consensus.', iconSymbol: '🎰' },
  { id: 'c2', title: "Cleopatra's Cyrpto Gold", category: 'Slots', rtp: 97.2, provider: 'DroidChain Labs', volatility: 'Medium', maxMultiplier: '5000x', popularityScore: 95, houseEdge: '2.8%', releaseYear: 2002, tagline: 'Pharaoh-themed golden multipliers with interactive bonus rounds.', iconSymbol: '🏺' },
  { id: 'c3', title: 'Golden Bananas 2000', category: 'Slots', rtp: 98.1, provider: 'Consensus Play 1999', volatility: 'Low', maxMultiplier: '2000x', popularityScore: 94, houseEdge: '1.9%', releaseYear: 1999, tagline: 'A nostalgic retro 3-reel wild banana payout adventure.', iconSymbol: '🍌' },
  { id: 'c4', title: 'Satoshi Treasure Seekers', category: 'Slots', rtp: 99.0, provider: 'PeerToPeer Gaming', volatility: 'Extreme', maxMultiplier: '30000x', popularityScore: 99, houseEdge: '1.0%', releaseYear: 2004, tagline: 'Crack Genesis block secrets to secure ultimate ledger multipliers.', iconSymbol: '🔑' },
  { id: 'c5', title: 'Cyberpunk Neon Reels', category: 'Slots', rtp: 97.4, provider: 'Satoshi Soft v2003', volatility: 'High', maxMultiplier: '8000x', popularityScore: 92, houseEdge: '2.6%', releaseYear: 2003, tagline: 'Rhythm and bass pulse behind high-energy payline systems.', iconSymbol: '🌆' },
  { id: 'c6', title: 'Consensus Reels Express', category: 'Slots', rtp: 98.2, provider: 'Mempool Matrix', volatility: 'Low', maxMultiplier: '1500x', popularityScore: 90, houseEdge: '1.8%', releaseYear: 1995, tagline: 'Fast transaction block cycles keep aligning winning paylines.', iconSymbol: '⛓️' },
  { id: 'c7', title: 'Space Invader Bonus Wilds', category: 'Slots', rtp: 96.8, provider: 'Pixel Arcade Inc.', volatility: 'Medium', maxMultiplier: '4500x', popularityScore: 96, houseEdge: '3.2%', releaseYear: 1991, tagline: 'Destroy incoming laser ships to trigger random matching symbols.', iconSymbol: '👾' },
  { id: 'c8', title: 'Flop-Disk Diamond Falls', category: 'Slots', rtp: 97.9, provider: 'Legacy Rom Systems', volatility: 'Medium', maxMultiplier: '6000x', popularityScore: 89, houseEdge: '2.1%', releaseYear: 1993, tagline: 'Retro storage floppy disks stack for interactive cascade wins.', iconSymbol: '💾' },
  { id: 'c9', title: 'Classic Wild Cherry 1996', category: 'Slots', rtp: 98.5, provider: 'Fruit Machine Co.', volatility: 'Low', maxMultiplier: '1200x', popularityScore: 93, houseEdge: '1.5%', releaseYear: 1996, tagline: 'Pure mechanical cherry pull emulation with perfect physical audio.', iconSymbol: '🍒' },
  { id: 'c10', title: 'Mega Joker Ledger Line', category: 'Slots', rtp: 99.1, provider: 'DroidChain Labs', volatility: 'Extreme', maxMultiplier: '20000x', popularityScore: 97, houseEdge: '0.9%', releaseYear: 2005, tagline: 'Double-up supermeters designed for absolute block yielders.', iconSymbol: '🃏' },
  { id: 'c11', title: 'Mortal Reels II', category: 'Slots', rtp: 96.2, provider: 'Arcade Bloodworks', volatility: 'Extreme', maxMultiplier: '12000x', popularityScore: 94, houseEdge: '3.8%', releaseYear: 1993, tagline: 'Finish the combo! High volatility fatality multiplier wheels.', iconSymbol: '🥋' },
  { id: 'c12', title: 'Pharaoh Cash Tomb', category: 'Slots', rtp: 97.5, provider: 'Nile Genesis', volatility: 'High', maxMultiplier: '7500x', popularityScore: 90, houseEdge: '2.5%', releaseYear: 2001, tagline: 'Hieroglyphic paylines hide mysterious scatter scarab multipliers.', iconSymbol: '👑' },
  { id: 'c13', title: 'Tomb Raider Treasures', category: 'Slots', rtp: 96.9, provider: 'Eidos Emulator Play', volatility: 'Medium', maxMultiplier: '5000x', popularityScore: 92, houseEdge: '3.1%', releaseYear: 1996, tagline: 'Raid lost polygon chambers to secure hidden gold coin urns.', iconSymbol: '🎒' },
  { id: 'c14', title: 'Golden Seven Blast 1990', category: 'Slots', rtp: 98.0, provider: 'Vintage Cabinets', volatility: 'Low', maxMultiplier: '1800x', popularityScore: 88, houseEdge: '2.0%', releaseYear: 1990, tagline: 'Classic retro 3x3 mechanical grid with high hit frequencies.', iconSymbol: '7️⃣' },
  { id: 'c15', title: 'Double Diamond Node Spin', category: 'Slots', rtp: 97.8, provider: 'Consensus Play 1999', volatility: 'Low', maxMultiplier: '3305x', popularityScore: 91, houseEdge: '2.2%', releaseYear: 1999, tagline: 'Wild double multipliers multiply your payout line up to 4x.', iconSymbol: '💎' },
  { id: 'c16', title: 'Super Mario Coins Slots', category: 'Slots', rtp: 97.1, provider: 'Pixel Arcade Inc.', volatility: 'Medium', maxMultiplier: '4000x', popularityScore: 96, houseEdge: '2.9%', releaseYear: 1992, tagline: 'Hit the flashing yellow custom block to trigger star multipliers!', iconSymbol: '🧱' },
  { id: 'c17', title: 'Starcraft Galaxy Gold', category: 'Slots', rtp: 96.6, provider: 'Mempool Matrix', volatility: 'High', maxMultiplier: '9500x', popularityScore: 95, houseEdge: '3.4%', releaseYear: 1998, tagline: 'Harvest mineral paylines and spawn golden Vespene geysers.', iconSymbol: '🛸' },
  { id: 'c18', title: 'Cyber Security Crypts', category: 'Slots', rtp: 98.4, provider: 'Legacy Rom Systems', volatility: 'High', maxMultiplier: '11000x', popularityScore: 89, houseEdge: '1.6%', releaseYear: 2004, tagline: 'Unlock cryptographic firewalls to claim safe deposit jackpots.', iconSymbol: '🔒' },
  { id: 'c19', title: 'Dolphin Reef Waves', category: 'Slots', rtp: 97.6, provider: 'Aqua Play Systems', volatility: 'Medium', maxMultiplier: '5500x', popularityScore: 90, houseEdge: '2.4%', releaseYear: 2003, tagline: 'Submerge into beautiful coral lines with wild jumping dolphin multipliers.', iconSymbol: '🐬' },
  { id: 'c20', title: 'Giga Fortune 2005', category: 'Slots', rtp: 95.8, provider: 'PeerToPeer Gaming', volatility: 'Extreme', maxMultiplier: '50000x', popularityScore: 98, houseEdge: '4.2%', releaseYear: 2005, tagline: 'The original millionaire maker emulator featuring progressive bonus wheels.', iconSymbol: '💰' },
  { id: 'c21', title: 'Chrono Trigger Timelines', category: 'Slots', rtp: 98.3, provider: 'Legacy Rom Systems', volatility: 'Medium', maxMultiplier: '8800x', popularityScore: 93, houseEdge: '1.7%', releaseYear: 1995, tagline: 'Spin through different operational eras to merge overlapping combos.', iconSymbol: '⏳' },
  { id: 'c22', title: 'Book of Droid Consensus', category: 'Slots', rtp: 97.0, provider: 'DroidChain Labs', volatility: 'High', maxMultiplier: '10000x', popularityScore: 97, houseEdge: '3.0%', releaseYear: 2005, tagline: 'Expanding special book symbols fill reels during on-chain free spins.', iconSymbol: '📖' },
  { id: 'c23', title: 'Imperial Dragon Dynasty', category: 'Slots', rtp: 96.4, provider: 'Ancient Play Co.', volatility: 'High', maxMultiplier: '9000x', popularityScore: 89, houseEdge: '3.6%', releaseYear: 2001, tagline: 'Golden dragons spit fire multipliers across horizontal pay alleys.', iconSymbol: '🐉' },
  { id: 'c24', title: 'Gonzo Ledger Quest', category: 'Slots', rtp: 97.3, provider: 'Satoshi Soft v2003', volatility: 'Medium', maxMultiplier: '6400x', popularityScore: 94, houseEdge: '2.7%', releaseYear: 2003, tagline: 'Avalanche retro blocks explode, magnifying line multipliers consecutively.', iconSymbol: '🗺️' },
  { id: 'c25', title: 'Fruit Cocktail Mix 2000', category: 'Slots', rtp: 98.8, provider: 'Veggie Spin', volatility: 'Low', maxMultiplier: '2500x', popularityScore: 91, houseEdge: '1.2%', releaseYear: 2000, tagline: 'Nostalgic high reward fruit slot with interactive fever games.', iconSymbol: '🍹' },

  // TABLE GAMES (25 games)
  { id: 'c26', title: "Satoshi's Classic Black Jack", category: 'Table Games', rtp: 99.6, provider: 'PeerToPeer Gaming', volatility: 'Low', maxMultiplier: '3x', popularityScore: 99, houseEdge: '0.4%', releaseYear: 2000, tagline: 'Authentic 3:2 blackjack split and double down with zero house bias.', iconSymbol: '🃏' },
  { id: 'c27', title: 'Consensus Baccarat Express', category: 'Table Games', rtp: 98.9, provider: 'Consensus Play 1999', volatility: 'Low', maxMultiplier: '9x', popularityScore: 91, houseEdge: '1.1%', releaseYear: 1999, tagline: 'Predict Player, Banker, or consensus Tie on fast block shuffles.', iconSymbol: '👔' },
  { id: 'c28', title: 'Degen On-Chain Baccarat', category: 'Table Games', rtp: 98.8, provider: 'DroidChain Labs', volatility: 'Medium', maxMultiplier: '12x', popularityScore: 88, houseEdge: '1.2%', releaseYear: 2002, tagline: 'High-roller tables featuring custom Side Bets and payout multipliers.', iconSymbol: '🥂' },
  { id: 'c29', title: 'Zero-Proof Ultimate Craps', category: 'Table Games', rtp: 99.4, provider: 'PeerToPeer Gaming', volatility: 'Medium', maxMultiplier: '30x', popularityScore: 95, houseEdge: '0.6%', releaseYear: 1998, tagline: 'Shoot signed random entropy dice to verify consensus passlines.', iconSymbol: '🎲' },
  { id: 'c30', title: 'Sonic Speed Roulette', category: 'Table Games', rtp: 97.3, provider: 'Pixel Arcade Inc.', volatility: 'High', maxMultiplier: '36x', popularityScore: 96, houseEdge: '2.7%', releaseYear: 1991, tagline: 'High velocity single-zero wheel with supersonic bonus ball multipliers.', iconSymbol: '🎡' },
  { id: 'c31', title: 'Satoshi Live Texas Holdem', category: 'Table Games', rtp: 99.1, provider: 'Satoshi Soft v1998', volatility: 'High', maxMultiplier: '500x', popularityScore: 98, houseEdge: '0.9%', releaseYear: 1998, tagline: 'Consensus computer card-counters test your holdem premium ranges.', iconSymbol: '♠️' },
  { id: 'c32', title: 'Vintage Video Poker Jacks', category: 'Table Games', rtp: 99.5, provider: 'Legacy Rom Systems', volatility: 'Low', maxMultiplier: '800x', popularityScore: 94, houseEdge: '0.5%', releaseYear: 1990, tagline: 'Classic pixelated draw poker layout. Royal flush pays the ultimate pot.', iconSymbol: '📺' },
  { id: 'c33', title: 'Deuces Wild Electra', category: 'Table Games', rtp: 99.3, provider: 'Legacy Rom Systems', volatility: 'Low', maxMultiplier: '400x', popularityScore: 89, houseEdge: '0.7%', releaseYear: 1993, tagline: 'All 2s behave as absolute wildcards. Easy combos, high payout ratios.', iconSymbol: '🃏' },
  { id: 'c34', title: '3-Card Crypto Brag', category: 'Table Games', rtp: 98.0, provider: 'Consensus Play 1999', volatility: 'Medium', maxMultiplier: '40x', popularityScore: 85, houseEdge: '2.0%', releaseYear: 1997, tagline: 'Retro fast-paced brag gameplay with immediate dynamic payouts.', iconSymbol: '🎴' },
  { id: 'c35', title: 'Red Dog Crypt-River', category: 'Table Games', rtp: 97.2, provider: 'DroidChain Labs', volatility: 'High', maxMultiplier: '11x', popularityScore: 82, houseEdge: '2.8%', releaseYear: 2001, tagline: 'Bet on the spread gap size between two on-chain cards.', iconSymbol: '🐕' },
  { id: 'c36', title: 'Consensus Casino War', category: 'Table Games', rtp: 97.9, provider: 'Fruit Machine Co.', volatility: 'Low', maxMultiplier: '10x', popularityScore: 87, houseEdge: '2.1%', releaseYear: 1996, tagline: 'Simple, lightning dry run battles. Draw card beats opponent card to win.', iconSymbol: '⚔️' },
  { id: 'c37', title: 'Pai Gow Poker Consensus', category: 'Table Games', rtp: 98.5, provider: 'Satoshi Soft', volatility: 'Low', maxMultiplier: '8x', popularityScore: 86, houseEdge: '1.5%', releaseYear: 2004, tagline: 'Split your seven on-chain cards into premium high and low-hands.', iconSymbol: 'Tiles' },
  { id: 'c38', title: 'Super Sic Bo Dice Multi', category: 'Table Games', rtp: 97.1, provider: 'Nile Genesis', volatility: 'High', maxMultiplier: '150x', popularityScore: 90, houseEdge: '2.9%', releaseYear: 2003, tagline: 'Ancient Chinese dice game layered with random lightning multiplier nodes.', iconSymbol: '🎰' },
  { id: 'c39', title: 'European Roulette Pro v2', category: 'Table Games', rtp: 97.3, provider: 'PeerToPeer Gaming', volatility: 'High', maxMultiplier: '36x', popularityScore: 94, houseEdge: '2.7%', releaseYear: 2005, tagline: 'Beautiful responsive single zero wheel with visual hot/cold heatmaps.', iconSymbol: '🎡' },
  { id: 'c40', title: 'American Double-Zero Wheel', category: 'Table Games', rtp: 94.7, provider: 'Vintage Cabinets', volatility: 'High', maxMultiplier: '36x', popularityScore: 88, houseEdge: '5.3%', releaseYear: 1990, tagline: 'Double-zero layout offering increased stakes and traditional mechanics.', iconSymbol: '🎠' },
  { id: 'c41', title: 'Zero-Knowledge Baccarat', category: 'Table Games', rtp: 98.9, provider: 'Cipher Tech v2005', volatility: 'Low', maxMultiplier: '9x', popularityScore: 91, houseEdge: '1.1%', releaseYear: 2005, tagline: 'zk-Proofs guarantee pre-shuffled digital deck states are tamper-proof.', iconSymbol: '🛡️' },
  { id: 'c42', title: 'Pontoon Retro Classic', category: 'Table Games', rtp: 99.6, provider: 'Vintage Cabinets', volatility: 'Medium', maxMultiplier: '4x', popularityScore: 89, houseEdge: '0.4%', releaseYear: 1994, tagline: 'Slick British Blackjack variation with custom double-down rules.', iconSymbol: '🎩' },
  { id: 'c43', title: 'Spanish Blackjack 21', category: 'Table Games', rtp: 99.6, provider: 'Legacy Rom Systems', volatility: 'Medium', maxMultiplier: '5x', popularityScore: 90, houseEdge: '0.4%', releaseYear: 1997, tagline: 'Spanish deck (no 10s) creates unique statistical strategic challenges.', iconSymbol: '🏓' },
  { id: 'c44', title: 'Multihand Video Poker 100x', category: 'Table Games', rtp: 99.2, provider: 'Consensus Play 1999', volatility: 'High', maxMultiplier: '1000x', popularityScore: 93, houseEdge: '0.8%', releaseYear: 1999, tagline: 'Play exactly 100 hands concurrently to hit multiple royal flushes.', iconSymbol: '🎴' },
  { id: 'c45', title: 'Aces & Faces Retro Draw', category: 'Table Games', rtp: 99.1, provider: 'Fruit Machine Co.', volatility: 'Low', maxMultiplier: '500x', popularityScore: 86, houseEdge: '0.9%', releaseYear: 1995, tagline: 'Increased odds on royal card combinations (Jacks, Queens, Kings, Aces).', iconSymbol: '👑' },
  { id: 'c46', title: 'Triple Card Poker Clash', category: 'Table Games', rtp: 98.0, provider: 'Mempool Matrix', volatility: 'Medium', maxMultiplier: '40x', popularityScore: 88, houseEdge: '2.0%', releaseYear: 2001, tagline: 'Deceptively simple 3-card poker with pair-plus on-chain multipliers.', iconSymbol: '🍀' },
  { id: 'c47', title: 'French La Partage Roulette', category: 'Table Games', rtp: 98.6, provider: 'PeerToPeer Gaming', volatility: 'Medium', maxMultiplier: '36x', popularityScore: 92, houseEdge: '1.4%', releaseYear: 2002, tagline: 'La Partage rule returns half even-money stakes on zero node drops.', iconSymbol: '🎠' },
  { id: 'c48', title: 'Pirate 21 Crypto Bounty', category: 'Table Games', rtp: 99.4, provider: 'Aqua Play Systems', volatility: 'Medium', maxMultiplier: '6x', popularityScore: 84, houseEdge: '0.6%', releaseYear: 2003, tagline: 'Sail pirate seas in a blackjack layout offering bonus deck payouts.', iconSymbol: '🏴‍☠️' },
  { id: 'c49', title: 'Oasis Poker Consensus Draft', category: 'Table Games', rtp: 98.4, provider: 'Cipher Tech v2005', volatility: 'Medium', maxMultiplier: '100x', popularityScore: 85, houseEdge: '1.6%', releaseYear: 2005, tagline: 'Swap on-chain cards before raising stakes against virtual dealers.', iconSymbol: '🌴' },
  { id: 'c50', title: 'Super Wheel Consensus Spin', category: 'Table Games', rtp: 97.8, provider: 'Consensus Play 1999', volatility: 'High', maxMultiplier: '47x', popularityScore: 89, houseEdge: '2.2%', releaseYear: 1998, tagline: 'Retro big-6 layout where numbers, suits, or symbols pay instant rewards.', iconSymbol: '🎡' },

  // INSTANT PLAY (20 games)
  { id: 'c51', title: 'Ethereum High-Lo Express', category: 'Instant Play', rtp: 98.5, provider: 'Consensus Play 1999', volatility: 'Low', maxMultiplier: '40x', popularityScore: 95, houseEdge: '1.5%', releaseYear: 1999, tagline: 'Pick higher or lower on sequential consensus hash indices.', iconSymbol: '📈' },
  { id: 'c52', title: 'Zero-Knowledge Scratch Card', category: 'Instant Play', rtp: 96.0, provider: 'Cipher Tech v2005', volatility: 'Extreme', maxMultiplier: '10000x', popularityScore: 92, houseEdge: '4.0%', releaseYear: 2005, tagline: 'Scratch shiny digital overlays verified instantly via cryptography.', iconSymbol: '🎫' },
  { id: 'c53', title: 'Mempool Gas Limit Minefield', category: 'Instant Play', rtp: 98.1, provider: 'Mempool Matrix', volatility: 'High', maxMultiplier: '2000x', popularityScore: 94, houseEdge: '1.9%', releaseYear: 2004, tagline: 'Navigate mined slots to securely compound yields without detonating.', iconSymbol: '💣' },
  { id: 'c54', title: 'Keno consensus Lottery 90s', category: 'Instant Play', rtp: 95.5, provider: 'Vintage Cabinets', volatility: 'Extreme', maxMultiplier: '50000x', popularityScore: 90, houseEdge: '4.5%', releaseYear: 1992, tagline: 'Pick ten block numbers and watch mechanical consensus balls align.', iconSymbol: '🎱' },
  { id: 'c55', title: 'Crypto Wheel Rocket', category: 'Instant Play', rtp: 97.4, provider: 'DroidChain Labs', volatility: 'Medium', maxMultiplier: '100x', popularityScore: 91, houseEdge: '2.6%', releaseYear: 2003, tagline: 'Select immediate speeds and payouts on a rapid revolving clock.', iconSymbol: '⚡' },
  { id: 'c56', title: 'Cyber Greyhound Racer', category: 'Instant Play', rtp: 96.2, provider: 'Legacy Rom Systems', volatility: 'High', maxMultiplier: '500x', popularityScore: 87, houseEdge: '3.8%', releaseYear: 1994, tagline: 'Pick virtual hounds running across retro 16-bit track buffers.', iconSymbol: '🐕' },
  { id: 'c57', title: 'Virtual Horse Derby 1997', category: 'Instant Play', rtp: 96.5, provider: 'Satoshi Soft v1998', volatility: 'High', maxMultiplier: '1000x', popularityScore: 93, houseEdge: '3.5%', releaseYear: 1997, tagline: 'Nostalgic 90s pixelated equestrian sprint with dynamic odds.', iconSymbol: '🐎' },
  { id: 'c58', title: 'Cyber Block Lotto', category: 'Instant Play', rtp: 95.0, provider: 'DroidChain Labs', volatility: 'Extreme', maxMultiplier: '100000x', popularityScore: 97, houseEdge: '5.0%', releaseYear: 2005, tagline: 'Decentralized national lottery pool matched directly with daily headers.', iconSymbol: '🎟️' },
  { id: 'c59', title: 'Consensus Coin Flip Live', category: 'Instant Play', rtp: 99.0, provider: 'PeerToPeer Gaming', volatility: 'Low', maxMultiplier: '2x', popularityScore: 98, houseEdge: '1.0%', releaseYear: 1996, tagline: 'Ultimate direct heads or tails choice with instant payouts.', iconSymbol: '🪙' },
  { id: 'c60', title: 'Retro Scratch Space Blast', category: 'Instant Play', rtp: 96.8, provider: 'Pixel Arcade Inc.', volatility: 'High', maxMultiplier: '5000x', popularityScore: 88, houseEdge: '3.2%', releaseYear: 1993, tagline: 'Alien-themed cards. Match exactly three laser ships to win!', iconSymbol: '👽' },
  { id: 'c61', title: 'Pac-Man Coin Collector', category: 'Instant Play', rtp: 97.9, provider: 'Fruit Machine Co.', volatility: 'Medium', maxMultiplier: '250x', popularityScore: 95, houseEdge: '2.1%', releaseYear: 1995, tagline: 'Munch dots along dynamic pathways. High speed, instant returns.', iconSymbol: '🍕' },
  { id: 'c62', title: 'Retro Pinball Payout', category: 'Instant Play', rtp: 97.0, provider: 'Legacy Rom Systems', volatility: 'Medium', maxMultiplier: '300x', popularityScore: 91, houseEdge: '3.0%', releaseYear: 1990, tagline: 'Launch steel balance balls into score multipliers and lightning triggers.', iconSymbol: '🎳' },
  { id: 'c63', title: 'Coin Splitter Extreme 2000', category: 'Instant Play', rtp: 98.2, provider: 'Mempool Matrix', volatility: 'Low', maxMultiplier: '10x', popularityScore: 89, houseEdge: '1.8%', releaseYear: 2000, tagline: 'Choose how many splits to apply to incoming digital block payouts.', iconSymbol: '✂️' },
  { id: 'c64', title: 'Lucky Clover Scratch', category: 'Instant Play', rtp: 95.9, provider: 'Veggie Spin', volatility: 'High', maxMultiplier: '3000x', popularityScore: 87, houseEdge: '4.1%', releaseYear: 1997, tagline: 'Match triple emerald clovers under static retro foil labels.', iconSymbol: '🍀' },
  { id: 'c65', title: 'Consensus Hi-Lo Poker', category: 'Instant Play', rtp: 98.4, provider: 'Consensus Play 1999', volatility: 'Low', maxMultiplier: '50x', popularityScore: 91, houseEdge: '1.6%', releaseYear: 1999, tagline: 'Will the next digital dealer suit card drop be higher or lower?', iconSymbol: '🃏' },
  { id: 'c66', title: 'Golden Seven Scratch-off', category: 'Instant Play', rtp: 96.3, provider: 'Vintage Cabinets', volatility: 'Extreme', maxMultiplier: '7777x', popularityScore: 92, houseEdge: '3.7%', releaseYear: 1992, tagline: 'Traditional ticket layout focusing purely on lucky number seven matches.', iconSymbol: '🎫' },
  { id: 'c67', title: 'Micro Balloon Burst', category: 'Instant Play', rtp: 98.0, provider: 'Aqua Play Systems', volatility: 'Medium', maxMultiplier: '100x', popularityScore: 90, houseEdge: '2.0%', releaseYear: 2002, tagline: 'Inflate digital balloons exponentially and pop them to safe out payout.', iconSymbol: '🎈' },
  { id: 'c68', title: 'Mega Mines Crypt', category: 'Instant Play', rtp: 98.6, provider: 'DroidChain Labs', volatility: 'High', maxMultiplier: '500x', popularityScore: 93, houseEdge: '1.4%', releaseYear: 2005, tagline: 'Uncover secure ledger nodes whilst side-stepping cryptographic traps.', iconSymbol: '🛸' },
  { id: 'c69', title: 'Diamond Miner Retro', category: 'Instant Play', rtp: 97.5, provider: 'Mempool Matrix', volatility: 'Medium', maxMultiplier: '150x', popularityScore: 85, houseEdge: '2.5%', releaseYear: 1994, tagline: 'Dig through pixelated dirt cells to uncover precious crystalline stones.', iconSymbol: '⛏️' },
  { id: 'c70', title: 'Satoshi Power Ball Lotto', category: 'Instant Play', rtp: 94.0, provider: 'Satoshi Soft', volatility: 'Extreme', maxMultiplier: '1000000x', popularityScore: 99, houseEdge: '6.0%', releaseYear: 2003, tagline: 'Choose exactly five prime numbers for massive block jackpots.', iconSymbol: '🎱' },

  // DICE & PLINKO (15 games)
  { id: 'c71', title: 'Consensus Plinko Mega Wall', category: 'Dice & Plinko', rtp: 98.9, provider: 'DroidChain Labs', volatility: 'Medium', maxMultiplier: '1000x', popularityScore: 98, houseEdge: '1.1%', releaseYear: 2001, tagline: 'Drop virtual round chips through pegged slots into high multi bins.', iconSymbol: '🔺' },
  { id: 'c72', title: 'Giga Plinko Stake', category: 'Dice & Plinko', rtp: 99.0, provider: 'PeerToPeer Gaming', volatility: 'Extreme', maxMultiplier: '5000x', popularityScore: 97, houseEdge: '1.0%', releaseYear: 2004, tagline: 'Peg obstacles drop chips with highly custom volatility parameters.', iconSymbol: '🔻' },
  { id: 'c73', title: 'Satoshi Dice Master', category: 'Dice & Plinko', rtp: 99.5, provider: 'PeerToPeer Gaming', volatility: 'Low', maxMultiplier: '100x', popularityScore: 97, houseEdge: '0.5%', releaseYear: 1998, tagline: 'Classic multi-roll under/over dice slider with 99.5% payout rates.', iconSymbol: '🎲' },
  { id: 'c74', title: 'POW Sic Bo Craps', category: 'Dice & Plinko', rtp: 97.5, provider: 'Legacy Rom Systems', volatility: 'High', maxMultiplier: '150x', popularityScore: 89, houseEdge: '2.5%', releaseYear: 1993, tagline: 'Nostalgic virtual shaker containing three deterministic dice elements.', iconSymbol: '🎲' },
  { id: 'c75', title: 'Laser Plinko 2000', category: 'Dice & Plinko', rtp: 98.2, provider: 'Pixel Arcade Inc.', volatility: 'Medium', maxMultiplier: '800x', popularityScore: 91, houseEdge: '1.8%', releaseYear: 2000, tagline: 'Futuristic retro grid styled with neon beam reflections.', iconSymbol: '⚡' },
  { id: 'c76', title: 'Dynamic Multiplier Craps', category: 'Dice & Plinko', rtp: 98.6, provider: 'Satoshi Soft v2003', volatility: 'Medium', maxMultiplier: '30x', popularityScore: 92, houseEdge: '1.4%', releaseYear: 2003, tagline: 'Roll lucky craps and accumulate consecutive multiplier milestones.', iconSymbol: '🎲' },
  { id: 'c77', title: 'Mempool Dice Sliders', category: 'Dice & Plinko', rtp: 99.1, provider: 'Mempool Matrix', volatility: 'Low', maxMultiplier: '50x', popularityScore: 88, houseEdge: '0.9%', releaseYear: 2005, tagline: 'Toggle win probability lines on-the-fly with precise RTP metrics.', iconSymbol: '🎚️' },
  { id: 'c78', title: 'Classic Chuck-A-Luck', category: 'Dice & Plinko', rtp: 96.9, provider: 'Vintage Cabinets', volatility: 'Medium', maxMultiplier: '12x', popularityScore: 85, houseEdge: '3.1%', releaseYear: 1990, tagline: 'Deterministic birdcage spinning action containing traditional retro dice.', iconSymbol: '🧺' },
  { id: 'c79', title: 'Crypto Hazard Dice Roll', category: 'Dice & Plinko', rtp: 97.8, provider: 'Consensus Play 1999', volatility: 'High', maxMultiplier: '180x', popularityScore: 86, houseEdge: '2.2%', releaseYear: 1999, tagline: 'Old English dice style. Call your hazard target and roll instantly.', iconSymbol: '🎲' },
  { id: 'c80', title: 'Plinko Deluxe Gold 1995', category: 'Dice & Plinko', rtp: 98.0, provider: 'Fruit Machine Co.', volatility: 'Low', maxMultiplier: '500x', popularityScore: 94, houseEdge: '2.0%', releaseYear: 1995, tagline: 'Vintage game show set with physical bouncy ball acoustics.', iconSymbol: '🔔' },
  { id: 'c81', title: 'Banker Dice Consensus', category: 'Dice & Plinko', rtp: 98.4, provider: 'Cipher Tech v2005', volatility: 'Low', maxMultiplier: '6x', popularityScore: 84, houseEdge: '1.6%', releaseYear: 2005, tagline: 'Direct dice combat against virtual casino bankers. Win ties.', iconSymbol: '🎲' },
  { id: 'c82', title: 'Pyramid Drop Plinko', category: 'Dice & Plinko', rtp: 98.7, provider: 'Nile Genesis', volatility: 'Medium', maxMultiplier: '1000x', popularityScore: 89, houseEdge: '1.3%', releaseYear: 2002, tagline: 'Set pyramid peg layers from 8 to 16 to maximize ultimate outcomes.', iconSymbol: '🔺' },
  { id: 'c83', title: 'Zero-Proof Rocket Dice', category: 'Dice & Plinko', rtp: 99.2, provider: 'PeerToPeer Gaming', volatility: 'Low', maxMultiplier: '99x', popularityScore: 93, houseEdge: '0.8%', releaseYear: 2004, tagline: 'Two fast rolling dice checked and verified by digital block hashes.', iconSymbol: '🚀' },
  { id: 'c84', title: 'Satoshi Macao Sic Bo', category: 'Dice & Plinko', rtp: 97.2, provider: 'Satoshi Soft v1998', volatility: 'High', maxMultiplier: '180x', popularityScore: 90, houseEdge: '2.8%', releaseYear: 1998, tagline: 'Traditional Macao layout tables featuring customizable betting blocks.', iconSymbol: '🎲' },
  { id: 'c85', title: 'Degen Double Dice Roll', category: 'Dice & Plinko', rtp: 98.3, provider: 'DroidChain Labs', volatility: 'Extreme', maxMultiplier: '250x', popularityScore: 91, houseEdge: '1.7%', releaseYear: 2005, tagline: 'Bank roll multiplier combos when double matching sixes are rolled.', iconSymbol: '🎰' },

  // RETRO ARCADE LIVE (15 games)
  { id: 'c86', title: 'On-Chain Pac-Man Slot Run', category: 'Retro Arcade Live', rtp: 97.5, provider: 'Pixel Arcade Inc.', volatility: 'Medium', maxMultiplier: '500x', popularityScore: 99, houseEdge: '2.5%', releaseYear: 1996, tagline: 'Munch dots down random tracks to trigger ghost multipliers.', iconSymbol: '🍕' },
  { id: 'c87', title: 'Sonic Spin Wheel Blitz', category: 'Retro Arcade Live', rtp: 98.0, provider: 'Pixel Arcade Inc.', volatility: 'Low', maxMultiplier: '200x', popularityScore: 98, houseEdge: '2.0%', releaseYear: 1991, tagline: 'Hyper velocity carousel spin featuring golden rings rewards.', iconSymbol: '🦔' },
  { id: 'c88', title: 'Warcraft Orcs War-Chest', category: 'Retro Arcade Live', rtp: 96.6, provider: 'Consensus Play 1999', volatility: 'High', maxMultiplier: '1200x', popularityScore: 93, houseEdge: '3.4%', releaseYear: 1995, tagline: 'Raid gold mine resource boxes to unlock magical orc chest prizes.', iconSymbol: '🛡️' },
  { id: 'c89', title: 'Super Mario Brick Breaker', category: 'Retro Arcade Live', rtp: 97.2, provider: 'Pixel Arcade Inc.', volatility: 'Medium', maxMultiplier: '450x', popularityScore: 96, houseEdge: '2.8%', releaseYear: 1990, tagline: 'Classic green sewer tunnel brick drops containing coins.', iconSymbol: '🧱' },
  { id: 'c90', title: 'DOOM Hellfire Chain-Spins', category: 'Retro Arcade Live', rtp: 96.1, provider: 'Legacy Rom Systems', volatility: 'Extreme', maxMultiplier: '10000x', popularityScore: 97, houseEdge: '3.9%', releaseYear: 1993, tagline: 'Heavy industrial thrash audio accompanies random plasma blast slots.', iconSymbol: '🔫' },
  { id: 'c91', title: 'GoldenEye Split-Screen Pot', category: 'Retro Arcade Live', rtp: 97.8, provider: 'Mempool Matrix', volatility: 'High', maxMultiplier: '1000x', popularityScore: 95, houseEdge: '2.2%', releaseYear: 1997, tagline: 'Aim at golden briefing cases to secure high multiplier pay schemes.', iconSymbol: '💼' },
  { id: 'c92', title: 'Zelda Chest Key Quest', category: 'Retro Arcade Live', rtp: 98.4, provider: 'Nile Genesis', volatility: 'Medium', maxMultiplier: '750x', popularityScore: 98, houseEdge: '1.6%', releaseYear: 1998, tagline: 'Pick a chest; find a crystal key; level up to next multiplier tier!', iconSymbol: '🗝️' },
  { id: 'c93', title: 'Crash Bandicoot Nitro Spin', category: 'Retro Arcade Live', rtp: 97.0, provider: 'Fruit Machine Co.', volatility: 'Medium', maxMultiplier: '350x', popularityScore: 92, houseEdge: '3.0%', releaseYear: 1998, tagline: 'Wumpa fruits collect. Dodge TNT boxes to keep multiplier runs safe.', iconSymbol: '🦊' },
  { id: 'c94', title: 'Deus Ex Cyber hacking Pots', category: 'Retro Arcade Live', rtp: 98.1, provider: 'Cipher Tech v2005', volatility: 'High', maxMultiplier: '1500x', popularityScore: 89, houseEdge: '1.9%', releaseYear: 2000, tagline: 'Connect cyber terminals securely to unlock high-yield deposit logs.', iconSymbol: '💻' },
  { id: 'c95', title: 'Tony Hawk Skate Combo multiplier', category: 'Retro Arcade Live', rtp: 97.9, provider: 'Vintage Cabinets', volatility: 'Low', maxMultiplier: '100x', popularityScore: 94, houseEdge: '2.1%', releaseYear: 2000, tagline: 'String skate tricks cleanly. Higher combo score = larger payout multiplication.', iconSymbol: '🛹' },
  { id: 'c96', title: 'Halo Ring Defense Reels', category: 'Retro Arcade Live', rtp: 96.7, provider: 'Satoshi Soft v1998', volatility: 'High', maxMultiplier: '2500x', popularityScore: 97, houseEdge: '3.3%', releaseYear: 2001, tagline: 'Assault alien battle cruisers and earn legendary master credit packs.', iconSymbol: '🪐' },
  { id: 'c97', title: 'GTA San Andreas Alley Craps', category: 'Retro Arcade Live', rtp: 98.2, provider: 'DroidChain Labs', volatility: 'Medium', maxMultiplier: '120x', popularityScore: 99, houseEdge: '1.8%', releaseYear: 2004, tagline: 'Couch shooter alleyway dice roll with local Grove street stakes.', iconSymbol: '🏙️' },
  { id: 'c98', title: 'Kingdom Hearts Core Spin', category: 'Retro Arcade Live', rtp: 97.6, provider: 'Legacy Rom Systems', volatility: 'Low', maxMultiplier: '300x', popularityScore: 93, houseEdge: '2.4%', releaseYear: 2002, tagline: 'Summon keyblade combinations to lock high reward payline vectors.', iconSymbol: '🗝️' },
  { id: 'c99', title: 'MGS Snake Camouflage Hunt', category: 'Retro Arcade Live', rtp: 98.3, provider: 'Consensus Play 1999', volatility: 'Medium', maxMultiplier: '800x', popularityScore: 95, houseEdge: '1.7%', releaseYear: 2004, tagline: 'Hide in tactical boxes under radar scans to double current bet rewards.', iconSymbol: '📦' },
  { id: 'c100', title: 'Guitar Hero Solos Reels', category: 'Retro Arcade Live', rtp: 97.4, provider: 'Nile Genesis', volatility: 'High', maxMultiplier: '5000x', popularityScore: 96, houseEdge: '2.6%', releaseYear: 2005, tagline: 'Perfect consecutive fret hits to launch the ultimate multiplier concert.', iconSymbol: '🎸' }
];
